### PR TITLE
Bug 2043428: Address Alibaba CSI driver operator review comments

### PR DESCRIPTION
**Pull request by RomanBednar**
Bumping dependencies to resolve failed CVE scan. See [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2043428) for details.

### CODE REVIEW

**Comment by jsafrane** [comment]
How does this PR remove jwt-go? I can still see it in go.sum.

**Comment by jsafrane** [comment]
(using as a guinea pig for new tests)
/refresh
/test all

**Comment by RomanBednar** [comment]
> How does this PR remove jwt-go? I can still see it in go.sum.

Well this one doesn't. There will have to be one more bump to effectively get rid of it. I've linked another PR in the first comment which I think should be merged too and then we bump here again.

**Comment by jsafrane** [comment]
>> How does this PR remove jwt-go? I can still see it in go.sum.

> @jsafrane Well this one doesn't. There will have to be one more bump to effectively get rid of it. I've linked another PR in the first comment which I think should be merged too and then we bump here again.

The linked PR updates gomega, which does not use jwt-go. jwt-go comes from library-go.

**Comment by RomanBednar** [comment]
> > > How does this PR remove jwt-go? I can still see it in go.sum.
> 
> > @jsafrane Well this one doesn't. There will have to be one more bump to effectively get rid of it. I've linked another PR in the first comment which I think should be merged too and then we bump here again.
> 
> The linked PR updates gomega, which does not use jwt-go. jwt-go comes from library-go.

Ok, bumping library-go instead.

**Comment by RomanBednar** [comment]
This CVE will be resolved along with other [package bumps](https://github.com/openshift/alibaba-disk-csi-driver-operator/pull/29)

**Pull request closed without merging**
